#!/bin/sh
g++ -std=c++11 ../src/stringplus.cc test.cc to_upper.cc to_lower.cc is_alpha.cc is_digit.cc is_alpha_digit.cc  is_lower.cc is_upper.cc capitalize.cc decapitalize.cc chop.cc clean.cc swap_case.cc -o runtests
